-- AlterTable
ALTER TABLE "Order" ALTER COLUMN "postage" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "productTotalsPrice" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "tax" SET DATA TYPE DOUBLE PRECISION;
